import type { Euler, Color, Vector3, MeshBasicMaterial, MeshLambertMaterial, MeshPhongMaterial, MeshStandardMaterial } from 'three';

export type Material = MeshBasicMaterial | MeshLambertMaterial | MeshPhongMaterial | MeshStandardMaterial | MeshPhongMaterial;

export type mapConfig = {
	cameraClip: [number, number],
	fov: number,
	forceRotationRatio: number,
	sceneFile?: string,
	additionnalLight?: string[],
	skybox?: [
		skybox_px: string,
		skybox_nx: string,
		skybox_py: string,
		skybox_ny: string,
		skybox_pz: string,
		skybox_nz: string,
	],
	skyboxAsEnvironment: boolean,
	EnvironmentColor: Color | number,
	lightDecayFactor: number,
	lightIntensityFactor: number,
	transitionSpeed: number,
	playCameraPosition: Vector3,
	playCameraRotation: Euler,
	pauseCameraPosition: Vector3,
	pauseCameraRotation: Euler,
	player1Material: Material,
	player2Material: Material,
	floorMaterial: Material,
	floorReflectivity: number,
	floorReflectorColor: Color | number,
	ballMaterial: Material,
	offsideOpacityMultiplier: number,
	gameScale: number,
	baseSize: [number, number],
	playerSize: [number, number],
	moveSteps: number,
	moveStatusRouding: boolean,
	scoreFont: string,
	scoreMaterial: Material,
	scorePositions: [Vector3, Vector3],
	scoreRotations: [Euler, Euler],
	avatarPositions: [Vector3, Vector3],
	avatarScale: number,
	textFont: string,
	textMaterial: Material,
	textPausePosition: Vector3,
	textPauseRotation: Euler,
	textPlayPosition: Vector3,
	textPlayRotation: Euler,
};
